apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: files
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - daan.se
      secretName: daan-se-tls
  rules:
    - host: daan.se
      http:
        paths:
          - path: {{ .Values.context }}(/|$)(.*)
            backend:
              serviceName: files
              servicePort: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: well-known
spec:
  tls:
    - hosts:
        - daan.se
        - www.daan.se
      secretName: daan-se-tls
  rules:
    - host: www.daan.se
      http:
        paths:
          - path: /.well-known
            backend:
              serviceName: files
              servicePort: http
    - host: daan.se
      http:
        paths:
          - path: /.well-known
            backend:
              serviceName: files
              servicePort: http
