apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: files
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - daan.se
      secretName: daan-se-tls
  rules:
    - host: daan.se
      http:
        paths:
          - path: {{ .Values.context }}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: files
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: well-known
spec:
  tls:
    - hosts:
        - daan.se
        - www.daan.se
      secretName: daan-se-tls
  rules:
    - host: www.daan.se
      http:
        paths:
          - path: /.well-known
            pathType: Exact
            backend:
              service:
                name: files
                port:
                  name: http
    - host: daan.se
      http:
        paths:
          - path: /.well-known
            pathType: Exact
            backend:
              service:
                name: files
                port:
                  name: http
