apiVersion: v1
kind: Service
metadata:
  name: files-headless
  labels:
    app: files
spec:
  ports:
    - port: 80
      name: http
  clusterIP: None
  selector:
    app: files
---
apiVersion: v1
kind: Service
metadata:
  name: files
  labels:
    app: files
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: files