apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: files
spec:
  selector:
    matchLabels:
      app: files
  serviceName: "files"
  replicas: 1
  template:
    metadata:
      labels:
        app: files
    spec:
      containers:
        - name: files
          image: httpd:2.4.46
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs/
              name: host
            - name: config
              mountPath: /usr/local/apache2/conf/httpd.conf
              subPath: httpd.conf
      volumes:
        - name: host
          hostPath:
            path: {{ .Values.hostPath }}
        - name: config
          configMap:
            name: files
