apiVersion: v1
kind: Secret
metadata:
  name: daan-se-tls
  namespace: default
data:
  tls.crt: {{ .Files.Get "daan.se.crt" | b64enc }}
  tls.key: {{ .Files.Get "daan.se.key" | b64enc }}
type: kubernetes.io/tls
